# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_auto_20200305_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='model_name',
            field=models.CharField(help_text='型号名称', max_length=60, verbose_name='型号名称'),
        ),
    ]
