# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(db_index=True, help_text='SN', max_length=120, unique=True, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.CharField(db_index=True, help_text='UUID', max_length=120, unique=True, verbose_name='UUID'),
        ),
    ]
