# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-09 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20200305_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'permissions': (('view_server', 'can view server'),)},
        ),
    ]
